[project]
name = "backend"
version = "0.1.0"
description = "RAG 知识库后端"

requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.2",
    "asyncpg>=0.31.0",
    "cos-python-sdk-v5>=1.9.44",
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.0.52",
    "uvicorn[standard]>=0.52.4",
]

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
module-root = ""