// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type ServerSentEventsResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateConversationData, CreateConversationErrors, CreateConversationResponses, DeleteConversationData, DeleteConversationErrors, DeleteConversationResponses, DeleteDocumentData, DeleteDocumentErrors, DeleteDocumentResponses, DownloadDocumentData, DownloadDocumentErrors, DownloadDocumentResponses, GetAgentGraphMermaidData, GetAgentGraphMermaidResponses, GetConversationData, GetConversationErrors, GetConversationResponses, GetDocumentChunkData, GetDocumentChunkErrors, GetDocumentChunkResponses, GetDocumentData, GetDocumentErrors, GetDocumentResponses, HealthAppData, HealthAppResponses, HealthCosData, HealthCosResponses, HealthDbData, HealthDbResponses, ListConversationsData, ListConversationsErrors, ListConversationsResponses, ListDocumentChunksData, ListDocumentChunksErrors, ListDocumentChunksResponses, ListDocumentsData, ListDocumentsErrors, ListDocumentsResponses, RetryDocumentData, RetryDocumentErrors, RetryDocumentResponses, StreamChatData, StreamChatErrors, StreamChatResponses, UploadDocumentData, UploadDocumentErrors, UploadDocumentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health
 */
export const healthApp = <ThrowOnError extends boolean = false>(options?: Options<HealthAppData, ThrowOnError>): RequestResult<HealthAppResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthAppResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Health Db
 *
 * 跑一句 SELECT 1 验证 DB 连通性。
 */
export const healthDb = <ThrowOnError extends boolean = false>(options?: Options<HealthDbData, ThrowOnError>): RequestResult<HealthDbResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthDbResponses, unknown, ThrowOnError>({ url: '/api/health/db', ...options });

/**
 * Health Cos
 *
 * 检查 COS 连通性；未配置时返回 not_configured 而非 500。
 */
export const healthCos = <ThrowOnError extends boolean = false>(options?: Options<HealthCosData, ThrowOnError>): RequestResult<HealthCosResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthCosResponses, unknown, ThrowOnError>({ url: '/api/health/cos', ...options });

/**
 * List Documents
 */
export const listDocuments = <ThrowOnError extends boolean = false>(options?: Options<ListDocumentsData, ThrowOnError>): RequestResult<ListDocumentsResponses, ListDocumentsErrors, ThrowOnError> => (options?.client ?? client).get<ListDocumentsResponses, ListDocumentsErrors, ThrowOnError>({ url: '/api/documents', ...options });

/**
 * Upload Document
 *
 * 上传文档：写入 COS、落库后立即返回，解析与向量化通过 BackgroundTasks 异步进行。
 */
export const uploadDocument = <ThrowOnError extends boolean = false>(options: Options<UploadDocumentData, ThrowOnError>): RequestResult<UploadDocumentResponses, UploadDocumentErrors, ThrowOnError> => (options.client ?? client).post<UploadDocumentResponses, UploadDocumentErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/documents',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete Document
 */
export const deleteDocument = <ThrowOnError extends boolean = false>(options: Options<DeleteDocumentData, ThrowOnError>): RequestResult<DeleteDocumentResponses, DeleteDocumentErrors, ThrowOnError> => (options.client ?? client).delete<DeleteDocumentResponses, DeleteDocumentErrors, ThrowOnError>({ url: '/api/documents/{document_id}', ...options });

/**
 * Get Document
 */
export const getDocument = <ThrowOnError extends boolean = false>(options: Options<GetDocumentData, ThrowOnError>): RequestResult<GetDocumentResponses, GetDocumentErrors, ThrowOnError> => (options.client ?? client).get<GetDocumentResponses, GetDocumentErrors, ThrowOnError>({ url: '/api/documents/{document_id}', ...options });

/**
 * Retry Document
 */
export const retryDocument = <ThrowOnError extends boolean = false>(options: Options<RetryDocumentData, ThrowOnError>): RequestResult<RetryDocumentResponses, RetryDocumentErrors, ThrowOnError> => (options.client ?? client).post<RetryDocumentResponses, RetryDocumentErrors, ThrowOnError>({ url: '/api/documents/{document_id}/retry', ...options });

/**
 * Download Document
 *
 * 返回文档原始字节。
 * - PDF / HTML / Markdown：可在浏览器内联预览
 * - DOCX：浏览器无法渲染，强制 attachment
 */
export const downloadDocument = <ThrowOnError extends boolean = false>(options: Options<DownloadDocumentData, ThrowOnError>): RequestResult<DownloadDocumentResponses, DownloadDocumentErrors, ThrowOnError> => (options.client ?? client).get<DownloadDocumentResponses, DownloadDocumentErrors, ThrowOnError>({ url: '/api/documents/{document_id}/file', ...options });

/**
 * List Document Chunks
 */
export const listDocumentChunks = <ThrowOnError extends boolean = false>(options: Options<ListDocumentChunksData, ThrowOnError>): RequestResult<ListDocumentChunksResponses, ListDocumentChunksErrors, ThrowOnError> => (options.client ?? client).get<ListDocumentChunksResponses, ListDocumentChunksErrors, ThrowOnError>({ url: '/api/documents/{document_id}/chunks', ...options });

/**
 * Get Document Chunk
 */
export const getDocumentChunk = <ThrowOnError extends boolean = false>(options: Options<GetDocumentChunkData, ThrowOnError>): RequestResult<GetDocumentChunkResponses, GetDocumentChunkErrors, ThrowOnError> => (options.client ?? client).get<GetDocumentChunkResponses, GetDocumentChunkErrors, ThrowOnError>({ url: '/api/documents/{document_id}/chunks/{chunk_id}', ...options });

/**
 * 按更新时间倒序分页列出所有会话
 */
export const listConversations = <ThrowOnError extends boolean = false>(options?: Options<ListConversationsData, ThrowOnError>): RequestResult<ListConversationsResponses, ListConversationsErrors, ThrowOnError> => (options?.client ?? client).get<ListConversationsResponses, ListConversationsErrors, ThrowOnError>({ url: '/api/conversations', ...options });

/**
 * Create Conversation
 */
export const createConversation = <ThrowOnError extends boolean = false>(options: Options<CreateConversationData, ThrowOnError>): RequestResult<CreateConversationResponses, CreateConversationErrors, ThrowOnError> => (options.client ?? client).post<CreateConversationResponses, CreateConversationErrors, ThrowOnError>({
    url: '/api/conversations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Conversation
 */
export const deleteConversation = <ThrowOnError extends boolean = false>(options: Options<DeleteConversationData, ThrowOnError>): RequestResult<DeleteConversationResponses, DeleteConversationErrors, ThrowOnError> => (options.client ?? client).delete<DeleteConversationResponses, DeleteConversationErrors, ThrowOnError>({ url: '/api/conversations/{conversation_id}', ...options });

/**
 * Get Conversation
 *
 * 返回会话本身 + 全部历史消息（含引用）。
 */
export const getConversation = <ThrowOnError extends boolean = false>(options: Options<GetConversationData, ThrowOnError>): RequestResult<GetConversationResponses, GetConversationErrors, ThrowOnError> => (options.client ?? client).get<GetConversationResponses, GetConversationErrors, ThrowOnError>({ url: '/api/conversations/{conversation_id}', ...options });

/**
 * Stream Chat
 *
 * SSE 流式问答。
 * 事件协议：message_start → citations → token...(多次) → message_end；
 * 任何阶段出错改 yield error。前端用 @microsoft/fetch-event-source 接。
 */
export const streamChat = <ThrowOnError extends boolean = false>(options: Options<StreamChatData, ThrowOnError, unknown>): Promise<ServerSentEventsResult<StreamChatResponses>> => (options.client ?? client).sse.post<StreamChatResponses, StreamChatErrors, ThrowOnError>({
    url: '/api/conversations/{conversation_id}/chat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Agent Graph Mermaid
 *
 * 输出 Agentic RAG 图结构的 Mermaid 文本，用于直观分析流程。
 */
export const getAgentGraphMermaid = <ThrowOnError extends boolean = false>(options?: Options<GetAgentGraphMermaidData, ThrowOnError>): RequestResult<GetAgentGraphMermaidResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAgentGraphMermaidResponses, unknown, ThrowOnError>({ url: '/api/agent/graph/mermaid', ...options });
