// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { HealthAppData, HealthAppResponses, HealthCosData, HealthCosResponses, HealthDbData, HealthDbResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health
 */
export const healthApp = <ThrowOnError extends boolean = false>(options?: Options<HealthAppData, ThrowOnError>): RequestResult<HealthAppResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthAppResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Health Db
 *
 * 跑一句 SELECT 1 验证 DB 连通性。
 */
export const healthDb = <ThrowOnError extends boolean = false>(options?: Options<HealthDbData, ThrowOnError>): RequestResult<HealthDbResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthDbResponses, unknown, ThrowOnError>({ url: '/api/health/db', ...options });

/**
 * Health Cos
 *
 * 检查 COS 连通性；未配置时返回 not_configured 而非 500。
 */
export const healthCos = <ThrowOnError extends boolean = false>(options?: Options<HealthCosData, ThrowOnError>): RequestResult<HealthCosResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthCosResponses, unknown, ThrowOnError>({ url: '/api/health/cos', ...options });
