"""add auth tables and permission tags

Revision ID: 1067f7754aaf
Revises: 896eb862fe09
Create Date: 2026-09-09 12:06:20.385439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1067f7754aaf'
down_revision: Union[str, Sequence[str], None] = '896eb862fe09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.Column('description', sa.String(length=256), nullable=False),
                    sa.Column('permission_tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )

    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=False),
                    sa.Column('password_hash', sa.String(length=255), nullable=False),
                    sa.Column('display_name', sa.String(length=128), nullable=False),
                    sa.Column('status', sa.String(length=16), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )

    op.create_table('user_roles',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('role_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'role_id')
                    )

    op.add_column('conversations', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('documents',
                  sa.Column('permission_tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('documents', sa.Column('created_by', sa.UUID(), nullable=True))
    # GIN 索引支持 permission_tags && user_tags 数组重叠查询
    op.execute(
        "CREATE INDEX ix_documents_permission_tags "
        "ON documents USING GIN (permission_tags)"
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'created_by')
    op.drop_column('documents', 'permission_tags')
    op.drop_column('conversations', 'user_id')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.execute("DROP INDEX IF EXISTS ix_documents_permission_tags")
    op.drop_table('user_roles')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
